apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-training-microservice
  namespace: teegarden
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-training-microservice
  template:
    metadata:
      labels:
        app: ai-training-microservice
    spec:
      containers:
        - name: ai-training-microservice
          image: gguardiola/ai-training-microservice:latest
          env:
            - name: env
              value: ${ENV}
            - name: MINIO_ACCESS_KEY
              value: ${MINIO_ACCESS_KEY}
            - name: MINIO_SECRET_KEY
              value: ${MINIO_SECRET_KEY}
            - name: PRODUCTION_EXTERNAL_IP
              value: ${PRODUCTION_EXTERNAL_IP}
            - name: API_SECRET
              value: ${API_SECRET}
          ports:
            - containerPort: 2080
