apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-training-microservice
  namespace: teegarden
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-training-microservice
  template:
    metadata:
      labels:
        app: ai-training-microservice
    spec:
      containers:
        - name: ai-training-microservice
          image: gguardiola/ai-training-microservice:latest
          env:
            - name: env
              value: tst
            - name: MINIO_ACCESS_KEY
              value: minioadmin
            - name: MINIO_SECRET_KEY
              value: minioadmin
            - name: PRODUCTION_EXTERNAL_IP
              value: 157.245.22.76
          ports:
            - containerPort: 2080
