services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - ai-training-microservice
    networks:
      - teegarden-namespace
  ai-training-microservice:
    depends_on:
      - mongodb
    container_name: ai-training-microservice
    image: ai-training-microservice:latest
    build:
      context: ./ai-training-microservice
      dockerfile: Dockerfile
    environment:
      - env=tst
    networks:
      - teegarden-namespace
  minio-bucket:
    container_name: minio-bucket
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data
    volumes:
      - minio_data:/data
    networks:
      - teegarden-namespace
  minio-sidecar:
    container_name: minio-sidecar
    image: minio/mc:latest
    depends_on:
      - minio-bucket
    entrypoint: >
      /bin/sh -c "
      sleep 5 &&
      mc alias set myminio http://minio-bucket:9000 minioadmin minioadmin &&
      mc ls myminio &&
      tail -f /dev/null &&
      echo "installing curl" &&
      apt-get update && apt-get install -y curl &&
      echo "curl installed"
      "
    networks:
      - teegarden-namespace      
  mongodb:
    container_name: mongodb
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    networks:
      - teegarden-namespace
volumes:
  mongodb_data:
    driver: local
  minio_data:
    driver: local

networks:
  teegarden-namespace:
    driver: bridge