apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: teegarden
spec:
  storageClassName: mongodb-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
