apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: teegarden
spec:
  storageClassName: minio-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
