name: Deploy to production k8s

on:
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Replace environment variables secrets
      run: |
        export ENV=${{ secrets.ENV }}
        export MINIO_ACCESS_KEY=${{ secrets.MINIO_ACCESS_KEY }}
        export MINIO_SECRET_KEY=${{ secrets.MINIO_SECRET_KEY }}
        export PRODUCTION_EXTERNAL_IP=${{ secrets.PRODUCTION_EXTERNAL_IP }}
        envsubst < .k8s/deployment.yaml      

    - name: Checking Kubeconfig
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > kubeconfig
        export KUBECONFIG=$PWD/kubeconfig

    - name: Apply deployment
      run: |
        kubectl apply -f .k8s
